server:
  port: ${PORT:8081}
  
logging:
  level: debug
spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:studentdb  

app:
  test:
    value: test value jonatan
    other-value:  test other value thaís
