server:
  port: ${PORT:8081}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    br.com.supero.superotemplate: DEBUG

spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:templatedb  

app:
  test:
    - value: Gorlami
    - other-value: test other value
